services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - mynetwork

  app:
    depends_on:
      - mysqldb
    build: ./
    restart: always
    ports:
      - 8092:8092
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    command: ["./wait-for-it.sh", "mysqldb:3306", "--", "java", "-jar", "/app.jar"]
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
